version: '3.8'

services:
  php-app:
    image: ${IMAGE_NAME}
    container_name: php-app
    ports:
      - "9000:9000"
    volumes:
      - /home/ubuntu/Task_Test_Josimar_Backend:/app

  nginx-app:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/Task_Test_Josimar_Backend:/app
      - /home/ubuntu/Task_Test_Josimar_Backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app