version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/ubuntu/app
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/home/ubuntu/app/database/database.sqlite

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/home/ubuntu/app/public
      - ./docker/nginx/brume.conf:/etc/nginx/conf.d/brume.conf
    depends_on:
      - app