version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - php-app

networks:
  app-network:
    driver: bridge
