version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite #Corrected database path.

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app