version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php-app

networks:
  app-network:
    driver: bridge