name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                cd /home/ec2-user/app
                git config --global --add safe.directory /home/ec2-user/app
                git pull origin main
                sudo chown -R ubuntu:ubuntu /home/ec2-user/app
                docker-compose -f docker-compose.yml down
                docker-compose -f docker-compose.yml up -d --build
                docker-compose -f docker-compose.yml exec app php artisan migrate --force
                docker-compose -f docker-compose.yml exec app php artisan optimize:clear