name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t brumebackend .
        docker tag brumebackend:latest ${{ secrets.DOCKERHUB_USERNAME }}/brumebackend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/brumebackend:latest

    - name: SSH to EC2 and install Docker
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY_PAIR_PEM }}
        script: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY_PAIR_PEM }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/brumebackend:latest
          docker stop brumebackend || true
          docker rm brumebackend || true
          docker run -d -p 80:80 --name brumebackend ${{ secrets.DOCKERHUB_USERNAME }}/brumebackend:latest