name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                sudo chown -R ubuntu:ubuntu /home/ec2-user/app
                cd /home/ec2-user/app
                git config --global --add safe.directory .
                git reset --hard HEAD
                git clean -fd
                git pull origin main
                docker-compose down
                docker-compose up -d --build
                docker-compose exec app php artisan migrate --force
                docker-compose exec app php artisan optimize:clear