name: Deploy Laravel to EC2 (SQLite)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_PAIR_PEM }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose nginx git
            sudo systemctl start docker
            sudo usermod -aG docker ubuntu
            sudo newgrp docker
            sudo mkdir -p /home/ubuntu/app
            sudo cd /home/ubuntu/app
            sudo rm -rf *
            sudo git clone --depth 1 https://github.com/renownjhoe/Task_Test_Josimar_Backend.git .
            sudo chown -R ubuntu:ubuntu /home/ubuntu/app
            sudo mv .env.docker .env
            sudo mkdir -p /etc/nginx/conf.d
            sudo mv docker/nginx/brume.conf /etc/nginx/conf.d/brume.conf
            sudo sed -i "s/your_domain_or_public_ip/${{ secrets.EC2_PUBLIC_IP }}/g" /etc/nginx/conf.d/brume.conf
            sudo systemctl restart nginx
            sudo docker-compose up -d --build

      - name: Test application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY_PAIR_PEM }}
          script: |
            curl http://${{ secrets.EC2_PUBLIC_IP }}/ #replace with a test endpoint.